interface DeviceInfo {
  dealer?: string;
  desc?: string;
  password: string;
}

export const device_match_password: Record<string, DeviceInfo> = {
  "Zrd90v": {"dealer": "测试咖啡机", "desc": "测试咖啡机", "password": "hoIppW"},
  "It76IV": {"dealer": "澳大利亚", "desc": "澳大利亚", "password": "IFhnws"},
  "yCG7bT": {"password": "0oAOLS"},
  "NULZJv": {"dealer": "文心桥", "desc": "柜体咖啡（文心桥）", "password": "xymWCm"},
  "aYsMO4": {"dealer": "深圳", "desc": "深圳", "password": "t2qbqt"},
  "gUwnQi": {"dealer": "西班牙冰淇淋", "desc": "西班牙冰淇淋", "password": "S9fPxP"},
  "qZemPx": {"dealer": "西班牙咖啡", "desc": "西班牙咖啡", "password": "w7bEiH"},
  "xZTDrv": {"dealer": "惠人", "desc": "惠人", "password": "PjrxbJ"},
  "jPepxj": {"dealer": "亚朵", "desc": "亚朵", "password": "ip0sWt"},
  "FQ8E90": {"dealer": "平谦", "desc": "平谦", "password": "rZYY98"},
  "WofgQK": {"dealer": "平迁主机", "password": "kGGPcs"},
  "qcOQrA": {"dealer": "余正1", "desc": "余正1", "password": "gz4q4M"},
  "x2GWRa": {"dealer": "扬州观前街", "desc": "扬州观前街", "password": "KA6gRl"},
  "wpTuc3": {"dealer": "冰淇淋", "desc": "冰淇淋", "password": "98z08u"},
  "74JQCC": {"dealer": "海中洲", "desc": "海中洲", "password": "cPjBn5"},
  "owgqmd": {"dealer": "办公室咖啡", "desc": "办公室咖啡", "password": "OMOTfs"},
  "BblyfH": {"dealer": "绍兴店2", "desc": "绍兴店", "password": "tEJSZi"},
  "1WbuJe": {"dealer": "绍兴3", "desc": "绍兴店3", "password": "BC91Dl"},
  "nitv1d": {"dealer": "绍兴4", "desc": "绍兴店", "password": "szhTQD"},
  "ntNPUO": {"dealer": "绍兴1", "desc": "绍兴店", "password": "YujteR"},
  "0AHLai": {"dealer": "马来西亚", "desc": "马来西亚单机咖啡", "password": "ZHfRyI"},
  "Zgqs4N": {"dealer": "水饺", "desc": "水饺", "password": "vRv33S"},
  "i2Aeg0": {"password": "CcZHeC", "dealer": "成都柜体咖啡", "desc": "成都柜体咖啡"},
  "H3Tcps": {"password": "b8880c", "dealer": "柜体咖啡10/22", "desc": "柜体咖啡10/22"},
  "CbiLVq": {"password": "lebai", "dealer": "伯高煮面", "desc": "伯高煮面"},
  "urHayl": {"password": "J8R2bN", "dealer": "普通咖啡11/06", "desc": "普通咖啡11/06"},
  "G6aqnm": {"password": "V1OfGQ", "dealer": "冰淇淋", "desc": "冰淇淋"},
  "pnxba7": {"password": "a9306b", "desc": "dipo煮面"},
  "9nJdnT": {"password": "bcfb46", "desc": "煮面"},
  "onenbK": {"password": "9af5c1", "desc": "星程煮面"},
  "cqS6qz": {"password": "tR22ZB", "dealer": "柜体咖啡", "desc": "成都柜体咖啡"},
  "3DYSZC": {"password": "zBE5nV", "dealer": "容州冰淇淋", "desc": "容州冰淇淋"},
  "6poZHS": {"password": "BAmGW8", "dealer": "煮面一体机", "desc": "煮面一体机"},
  "8PTwwz": {"password": "dcra7c", "desc": "机器大咖测试"},
  "qBKJZj": {"password": "NvOEgI", "dealer": "机器大咖", "desc": "机器大咖"},
  "90w5HH": {"password": "101c0b", "dealer": "竖屏冰激淋", "desc": "竖屏冰激淋"},
  "MuxB32": {"password": "CA2e7D", "dealer": "机器大咖", "desc": "机器大咖测试"},
  "k46fnx": {"password": "k6l30T", "dealer": "机器大咖", "desc": "机器大咖测试"},
  "RnpYtL": {"password": "FYdKqn", "dealer": "机器大咖", "desc": "机器大咖测试"},
  "gQo5Y3": {"password": "XICg3F", "desc": "2025煮面"},
  "ajy6Fb": {"password": "m2AUvO", "desc": "新机箱机器大咖南通"},
  "VIYeI1": {"password": "Y1a2Zk", "desc": "冰激淋1/13"},
  "yVS62Q": {"password": "LQLU5l", "desc": "冰激淋1/13"},
  "Nb6zJn": {"password": "x6EAxc", "desc": "天津冰激淋1/13"},
  "5esUXX": {"password": "NFnaKL", "desc": "冰激淋1/14"},
  "FjSfGD": {"password": "gZ8Zxz", "dealer": "加拿大", "desc": "加拿大"},
  "H2lDPX": {"password": "4Nx5Zu", "dealer": "南通咖啡", "desc": "南通咖啡"},
  "rk3588SDvision2": {"password": "temppwd", "dealer": "SDvision2", "desc": "SDvision2"},

  "ZupZDs": {"password": "cQuv4J", "dealer": "", "desc": "2025/3/26"},
  "owfS1r": {"password": "va40rE", "dealer": "", "desc": "2025/3/26冰淇淋"},
  "eW1zDe": {"password": "RmWBu7", "dealer": "", "desc": "2025/3/26冰淇淋"},
  "wKBcXa": {"password": "TkKx9F", "dealer": "", "desc": "2025/3/26冰淇淋"},

} 
